services:
  mongo:
    container_name: mongo
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - app-network

  auction-app:
    container_name: auction-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - AUCTION_DURATION_MINUTES=1
      - MONGODB_URL=mongodb://admin:admin@mongo:27017/auctions?authSource=admin
    depends_on:
      - mongo
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
